"""created serlilizations

Revision ID: 212727465ecd
Revises: 6c3f2746c946
Create Date: 2023-10-02 02:35:04.880224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212727465ecd'
down_revision = '6c3f2746c946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
